export const AnimaBanner = () => {
  return (
    <div className="box-border caret-transparent mb-12">
      <div className="fixed items-center bg-slate-900 border-b-indigo-600 border-l-gray-200 border-r-gray-200 border-t-gray-200 box-border caret-transparent gap-x-1.5 flex h-12 justify-center gap-y-1.5 z-[9999] border-b-[3px] border-solid top-0 inset-x-0 md:gap-x-2.5 md:gap-y-2.5">
        <div className="relative text-slate-100 text-xs box-border caret-transparent leading-[normal] text-center w-fit font-inter md:text-sm">
          Generated by
        </div>
        <div className="relative box-border caret-transparent h-6 w-[150px] md:w-[175px]">
          <img
            src="https://c.animaapp.com/mi0dh37lZbc34b/assets/anima-logo.svg"
            className="absolute box-border caret-transparent h-6 max-w-full w-6 left-0 top-0"
          />
          <div className="absolute text-white text-[15px] font-semibold box-border caret-transparent leading-[15.8px] text-nowrap left-7 top-[3px] font-mulish md:text-[17px]">
            anima
          </div>
          <div className="absolute text-violet-400 text-[17px] font-semibold box-border caret-transparent hidden leading-[15.8px] text-nowrap left-[84px] top-[3px] font-mulish md:block">
            playground
          </div>
        </div>
        <p className="relative text-slate-100 text-xs box-border caret-transparent hidden leading-[normal] min-h-0 min-w-0 text-center w-fit font-inter md:text-sm md:block md:min-h-[auto] md:min-w-[auto]">
          Turn your own designs to code today
        </p>
        <a
          href="https://www.animaapp.com/an?url=https%3A%2F%2Fwww.animaapp.com&utm_content=frosty-night-9241.dev.animaapp.io&utm_medium=anima-playground&utm_source=free-website-banner"
          className="relative items-center bg-indigo-700 box-border caret-transparent gap-x-2 flex shrink-0 h-7 justify-center gap-y-2 px-3 rounded-md"
        >
          <div className="relative text-neutral-200 text-xs font-semibold box-border caret-transparent leading-[19.2px] text-nowrap w-fit font-mulish">
            Start now
          </div>
        </a>
      </div>
    </div>
  );
};
